apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-deployment
  labels:
    app: mon-app
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
        environment: production
    spec:
      containers:
      - name: mon-app
        image: kaoutar02/mon-app-node:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "0.2"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 3000

